import React, { useMemo, useState } from 'react'
import { useAuth } from '../../../hooks/useAuth'
import { useEmployeeCommunications } from '../../../hooks/useEmployeeCommunications'
import { BookOpenCheck, CheckCircle2, FileText, GraduationCap, Megaphone, X } from 'lucide-react'
import { statusTone } from '../../../lib/communications'

const iconFor = (type) => type === 'letter' ? FileText : type === 'policy' ? BookOpenCheck : type === 'training' ? GraduationCap : Megaphone
const titleFor = (delivery) => delivery?.titleSnapshot || (delivery?.sourceType === 'policy' ? 'Policy document' : delivery?.sourceType === 'training' ? 'Training invitation' : 'HR update')

export default function EmployeeCommunicationsView({ employeeId }) {
  const { user } = useAuth()
  const { deliveries, acknowledge: acknowledgeDelivery, loading } = useEmployeeCommunications(user?.orgId, employeeId)
  const [selected, setSelected] = useState(null)
  const inbox = useMemo(() => deliveries.map((delivery) => ({ delivery })).sort((a, b) => (b.delivery.updatedAt?.seconds || 0) - (a.delivery.updatedAt?.seconds || 0)), [deliveries])

  const acknowledge = async (deliveryId) => {
    try { await acknowledgeDelivery(deliveryId); setSelected((current) => current ? { ...current, delivery: { ...current.delivery, status: 'acknowledged' } } : null) } catch (error) { alert(error?.message || 'Unable to record acknowledgement.') }
  }

  if (loading) return <div className="rounded-[12px] border border-gray-100 bg-white p-8 text-center text-[12px] font-medium text-slate-500">Loading documents and updates…</div>
  return <div className="mx-auto max-w-5xl space-y-4"><div className="rounded-[12px] border border-gray-100 bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-widest text-indigo-600">Employee inbox</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-slate-900">Documents & Updates</h2><p className="mt-2 text-[12px] leading-5 text-slate-500">Your issued HR letters, required reading, announcements, and training invitations appear here.</p></div>{inbox.length === 0 ? <div className="rounded-[12px] border border-gray-100 bg-white p-10 text-center shadow-sm"><FileText className="mx-auto text-slate-300" size={28} /><p className="mt-3 text-[13px] font-semibold text-slate-700">No documents or updates yet</p><p className="mt-1 text-[12px] text-slate-400">HR communications sent to you will appear here.</p></div> : <div className="overflow-hidden rounded-[12px] border border-gray-100 bg-white shadow-sm">{inbox.map(({ delivery }) => { const Icon = iconFor(delivery.sourceType); const needsAcknowledgement = delivery.acknowledgementMode === 'acknowledged' && delivery.status !== 'acknowledged'; return <button key={delivery.id} type="button" onClick={() => setSelected({ delivery })} className="flex w-full items-start gap-3 border-b border-slate-100 px-4 py-4 text-left last:border-b-0 hover:bg-slate-50"><div className="mt-0.5 rounded-lg bg-indigo-50 p-2 text-indigo-600"><Icon size={16} /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="truncate text-[13px] font-semibold text-slate-800">{titleFor(delivery)}</p><span className={`shrink-0 rounded-full border px-2 py-0.5 text-[9px] font-bold uppercase tracking-wide ${statusTone(needsAcknowledgement ? 'pending_approval' : delivery.status)}`}>{needsAcknowledgement ? 'Action required' : delivery.status}</span></div><p className="mt-1 line-clamp-2 text-[11px] leading-5 text-slate-500">{delivery.bodySnapshot || 'Open to view this HR communication.'}</p></div></button> })}</div>}</div>
  {selected && <div className="fixed inset-0 z-[120] flex items-end bg-slate-950/30 p-0 sm:items-center sm:justify-center sm:p-6"><div className="max-h-[88vh] w-full overflow-y-auto rounded-t-[16px] bg-white p-5 shadow-2xl sm:max-w-xl sm:rounded-[16px]"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-widest text-indigo-600">{selected.delivery.sourceType}</p><h3 className="mt-1 text-lg font-semibold text-slate-900">{titleFor(selected.delivery)}</h3></div><button type="button" onClick={() => setSelected(null)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={18} /></button></div><div className="mt-5 whitespace-pre-wrap rounded-lg border border-slate-100 bg-slate-50/50 p-4 text-[13px] leading-6 text-slate-700">{selected.delivery.bodySnapshot || 'No additional content was included.'}</div>{selected.delivery.acknowledgementMode === 'acknowledged' && selected.delivery.status !== 'acknowledged' && <button type="button" onClick={() => acknowledge(selected.delivery.id)} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 text-[12px] font-semibold text-white hover:bg-emerald-700"><CheckCircle2 size={16} /> I have read and understood</button>}{selected.delivery.acknowledgementMode !== 'acknowledged' && <p className="mt-5 text-center text-[11px] font-medium text-slate-400">Opened in your HRFlow employee inbox.</p>}</div></div>}
}
